# Generated by Django 5.1.6 on 2025-05-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datas",
            name="Description",
            field=models.CharField(default="", max_length=200),
        ),
    ]
